# config/sites.yaml
sites:
  - name: "The Body Shop AU"
    key: "thebodyshop"
    url: "https://www.thebodyshop.com.au/pages/offers"
  - name: "Supercheap Auto"
    key: "supercheapauto"
    url: "https://www.supercheapauto.com.au/sale"
  - name: "Automotive Superstore"
    key: "automotivesuperstore"
    url: "https://automotivesuperstore.com.au/?filterVid=28688"
  - name: "Woolworths Half Price Specials"
    key: "woolworths"
    url: "https://www.woolworths.com.au/shop/browse/specials/half-price"
  - name: "Coles Half Price Specials"
    key: "coles"
    url: "https://www.coles.com.au/on-special?filter_Special=halfprice&page=1"
